
import { AwarenessProfile } from "@/types";

// export const dummyAwarenessProfiles: AwarenessProfile[] = [
//     {
//         id: "awareness-profile-1",
//         name: "Cybersecurity Fundamentals Training",
//         description: "Comprehensive cybersecurity awareness program covering essential security practices, phishing detection, and password management for all employees.",
//         category: "security",
//         isActive: true,
//         courses: [
//             courses.find(c => c.id === "one-time-password")!,
//             courses.find(c => c.id === "phishing")!,
//             courses.find(c => c.id === "work-from-home-jobs")!,
//             courses.find(c => c.id === "physical-security")!,
//             courses.find(c => c.id === "information-security")!,
//         ],
//         startDate: new Date("2025-01-01"),
//         endDate: new Date("2025-03-31"),
//         employeeGroups: [],
//     },
//     {
//         id: "awareness-profile-2",
//         name: "Advanced Threat Protection Program",
//         description: "Deep dive into advanced cybersecurity threats including Business Email Compromise, insider threats, and backdoor attacks for security teams.",
//         category: "security",
//         isActive: true,
//         courses: [
//             courses.find(c => c.id === "business-email-compromise")!,
//             courses.find(c => c.id === "insider-threat")!,
//             courses.find(c => c.id === "backdoor-attacks")!,
//             courses.find(c => c.id === "ceo-fraud")!,
//             courses.find(c => c.id === "phishing")!,
//         ],
//         startDate: new Date("2025-02-01"),
//         endDate: new Date("2026-05-31"),    
//         employeeGroups: [],
//     },
//     {
//         id: "awareness-profile-3",
//         name: "AI & Machine Learning Awareness Initiative",
//         description: "Introduction to Generative AI, Dark AI threats, and best practices for safe AI adoption in the workplace.",
//         category: "ai",
//         isActive: true,
//         courses: [
//             courses.find(c => c.id === "generative-ai")!,
//             courses.find(c => c.id === "dark-ai")!,
//         ],
//         startDate: new Date("2025-03-01"),
//         endDate: new Date("2025-06-30"),
//         employeeGroups: [],
//     },
//     {
//         id: "awareness-profile-4",
//         name: "Cyber Hygiene Best Practices",
//         description: "Essential cyber hygiene practices covering password management, software updates, data access control, and email security.",
//         category: "security",
//         isActive: true,
//         courses: [
//             courses.find(c => c.id === "cyber-hygiene")!,
//             courses.find(c => c.id === "one-time-password")!,
//             courses.find(c => c.id === "work-from-home-jobs")!,
//         ],
//         startDate: new Date("2024-01-15"),
//         endDate: new Date("2024-04-15"),
//         employeeGroups: [],  
//     },
//     {
//         id: "awareness-profile-5",
//         name: "Attack Prevention & Defense Strategies",
//         description: "Comprehensive training on preventing and defending against brute force attacks, clickjacking, and adware in the workplace.",
//         category: "security",
//         isActive: true,
//         courses: [
//             courses.find(c => c.id === "brute-force")!,
//             courses.find(c => c.id === "clickjacking")!,
//             courses.find(c => c.id === "adware-in-the-workplace")!,
//         ],
//         startDate: new Date("2025-04-01"),
//         endDate: new Date("2025-12-31"),
//         employeeGroups: [],
//     },
//     {
//         id: "awareness-profile-6",
//         name: "Scam Awareness & Fraud Prevention",
//         description: "Training program focused on identifying and preventing digital scams including CEO fraud and digital arrest scams.",
//         category: "security",
//         isActive: true,
//         courses: [
//             courses.find(c => c.id === "ceo-fraud")!,
//             courses.find(c => c.id === "digital-arrest")!,
//         ],
//         startDate: new Date("2025-02-15"),
//         endDate: new Date("2025-12-31"),
//         employeeGroups: [],
//     },
//     {
//         id: "awareness-profile-7",
//         name: "Developer Security Essentials",
//         description: "Security awareness for developers covering browser extension safety, secure coding practices, and workplace compliance.",
//         category: "development",
//         isActive: true,
//         courses: [
//             courses.find(c => c.id === "browser-extension")!,
//             courses.find(c => c.id === "information-security")!,
//             courses.find(c => c.id === "physical-security")!,
//         ],
//         startDate: new Date("2025-05-01"),
//         endDate: new Date("2025-12-31"),
//         employeeGroups: [],
//     },
//     {
//         id: "awareness-profile-8",
//         name: "Quarterly Security Refresher Q2 2024",
//         description: "Quarterly refresher course covering the most critical security topics and emerging threats for all staff members.",
//         category: "security",
//         isActive: true,
//         courses: [
//             courses.find(c => c.id === "phishing")!,
//             courses.find(c => c.id === "business-email-compromise")!,
//             courses.find(c => c.id === "cyber-hygiene")!,
//             courses.find(c => c.id === "dark-ai")!,
//             courses.find(c => c.id === "digital-arrest")!,
//             courses.find(c => c.id === "one-time-password")!,
//         ],
//         startDate: new Date("2025-04-01"),
//         endDate: new Date("2026-12-31"),
//         employeeGroups: [],
//     },
// ];

// export const awarenessProfileFilterGroups: FilterGroup[] = [
//     {
//         title: "Category",
//         key: "category",
//         options: [
//             { label: "Security", value: "security", count: 6 },
//             { label: "AI", value: "ai", count: 1 },
//             { label: "Development", value: "development", count: 1 },
//         ],
//     },
//     {
//         title: "Status",
//         key: "isActive",
//         options: [
//             { label: "Active", value: "true", count: 7 },
//             { label: "Inactive", value: "false", count: 1 },
//         ],
//     },
//     {
//         title: "Duration",
//         key: "duration",
//         options: [
//             { label: "1-3 Months", value: "short", count: 3 },
//             { label: "3-4 Months", value: "medium", count: 4 },
//             { label: "4+ Months", value: "long", count: 1 },
//         ],
//     },
//     {
//         title: "Course Count",
//         key: "courseCount",
//         options: [
//             { label: "1-4 Courses", value: "small", count: 2 },
//             { label: "5-7 Courses", value: "medium", count: 4 },
//             { label: "8+ Courses", value: "large", count: 2 },
//         ],
//     },
//     {
//         title: "Start Quarter",
//         key: "startQuarter",
//         options: [
//             { label: "Q1 2024", value: "q1-2024", count: 3 },
//             { label: "Q2 2024", value: "q2-2024", count: 5 },
//         ],
//     },
//     {
//         title: "Training Level",
//         key: "trainingLevel",
//         options: [
//             { label: "Fundamentals", value: "fundamentals", count: 2 },
//             { label: "Intermediate", value: "intermediate", count: 3 },
//             { label: "Advanced", value: "advanced", count: 3 },
//         ],
//     },
// ];