import { Course, FilterGroup } from "@/types";

export const dummyCourses: Course[] = [
    {
        id: "one-time-password",
        name: "One Time Password",
        description: "Learn about One Time Password (OTP) security mechanisms and best practices for implementing secure authentication systems.",
        category: "security",
        level: "Beginner",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/One%20Time%20Password/One%20time%20password%20-%20thumbnail.png",
        slug: "one-time-password",
        updated_at: new Date().toISOString(),
    },
    {
        id: "work-from-home-jobs",
        name: "Work From Home Jobs",
        description: "Understand security risks and best practices when working from home, including protecting company data and maintaining secure remote connections.",
        category: "security",
        level: "beginner",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/WFH%20Security%20Tips/WFH%20Security%20Tips%20Thumbnail.png",
        slug: "work-from-home-jobs",
        updated_at: new Date().toISOString(),
    },
    {
        id: "business-email-compromise",
        name: "Business Email Compromise",
        description: "Learn to identify and prevent Business Email Compromise attacks, protecting your organization from email-based fraud and social engineering.",
        category: "security",
        level: "intermediate",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/BEC/Thumbnail/BEC%201.png",
        slug: "business-email-compromise",
        updated_at: new Date().toISOString(),
    },
    {
        id: "browser-extension",
        name: "Browser Extension",
        description: "Understand the security implications of browser extensions, including safe browsing practices and identifying potentially malicious extensions.",
        category: "ai",
        level: "Intermediate",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Browser%20Extension/Thumbnail/Browser%20Extensions%20(1).png",
        slug: "browser-extension",
        updated_at: new Date().toISOString(),
    },
    {
        id: "clickjacking",
        name: "Clickjacking",
        description: "Learn about clickjacking attacks and how to protect users from this deceptive web-based attack technique.",
        category: "security",
        level: "intermediate",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Clickjacking/Thumbnail/1%20Video%20Thumbnails.png",
        slug: "clickjacking",
        updated_at: new Date().toISOString(),
    },
    {
        id: "ceo-fraud",
        name: "CEO Fraud",
        description: "Understand CEO fraud tactics and learn to identify and prevent executive impersonation attacks targeting organizations.",
        category: "security",
        level: "intermediate",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Cybersecurity%20awareness%20CEO%20fraud/Cybersecurity%20awareness%20CEO%20fraud.png",
        slug: "ceo-fraud",
        updated_at: new Date().toISOString(),
    },
    {
        id: "generative-ai",
        name: "Generative AI",
        description: "Explore the security implications and best practices for using generative AI tools in the workplace safely and responsibly.",
        category: "ai",
        level: "Intermediate",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Generative%20AI/Thumbnail/Generative%20AI%20in%20Cybersecurity%201.png",
        slug: "generative-ai",
        updated_at: new Date().toISOString(),
    },
    {
        id: "harpstrings",
        name: "Harpstrings",
        description: "Learn about harpstrings security concepts and implementing effective security measures in your organization.",
        category: "security",
        level: "Advanced",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Malvertising/Malvertising%20Thumbnail.png",
        slug: "harpstrings",
        updated_at: new Date().toISOString(),
    },
    {
        id: "information-security",
        name: "Information Security",
        description: "Comprehensive introduction to information security principles, covering essential security awareness topics for all employees.",
        category: "security",   
        level: "beginner",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Information%20Security%20Awareness/Information%20Security%20Awareness%20-%20Thumbnail.png",
        slug: "information-security",
        updated_at: new Date().toISOString(),
    },
    {
        id: "physical-security",
        name: "Physical Security",
        description: "Learn about physical security measures to protect your workplace, including access control and security best practices.",
        category: "security",
        level: "beginner",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Physical%20Attack/Physical%20Attack%20Thumbnail.png",
        slug: "physical-security",
        updated_at: new Date().toISOString(),
    },
    {
        id: "insider-threat",
        name: "Insider Threat",
        description: "Understand insider threats, including red flags and real cases, and learn how to identify and defend against internal security risks.",
        category: "security",
        level: "Intermediate",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Insider%20Threats/Thumbnail/Insider%20Threat%2004.png",
        slug: "insider-threat",
        updated_at: new Date().toISOString(),
    },
    {
        id: "phishing",
        name: "Phishing",
        description: "Learn to identify and defend against phishing attacks, including various types of phishing threats and social engineering tactics.",
        category: "security",
        level: "beginner",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Phishing/Phishing%20Thumbnail.png",
        slug: "phishing",
        updated_at: new Date().toISOString(),
    },
    {
        id: "adware-in-the-workplace",
        name: "Adware in the Workplace",
        description: "Learn how to identify and prevent adware infections in workplace devices and understand security risks associated with adware.",
        category: "security",
        level: "intermediate",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Adware%20in%20the%20Workplace/Thumbnails/Adware%204.png",
        slug: "adware-in-the-workplace",
        updated_at: new Date().toISOString(),
    },
    {
        id: "backdoor-attacks",
        name: "Backdoor Attacks",
        description: "Understand backdoor attacks, how they work, and learn effective techniques to secure systems and prevent unauthorized access.",
        category: "security",
        level: "advanced",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Backdoor%20Attacks/Thumbnails/Backdoor%204.png",
        slug: "backdoor-attacks",
        updated_at: new Date().toISOString(),
    },
    {
        id: "brute-force",
        name: "Brute Force",
        description: "Learn about brute force attacks, password security, and how to implement strong authentication measures to protect against these attacks.",
        category: "security",
        level: "intermediate",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Brute%20force%20Attack/Thumbnail/Brute%20Force%20Attack%204.png",
        slug: "brute-force",
        updated_at: new Date().toISOString(),
    },
    {
        id: "cyber-hygiene",
        name: "Cyber Hygiene",
        description: "Learn essential cyber hygiene practices including password management, software updates, and maintaining good security habits.",
        category: "security",
        level: "beginner",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Cyber%20Hygiene/Thumbnail/Cyber%20Hygiene%204.png",
        slug: "cyber-hygiene",
        updated_at: new Date().toISOString(),
    },
    {
        id: "dark-ai",
        name: "Dark AI",
        description: "Explore the darker side of AI technology, understanding threats and defenses against malicious use of artificial intelligence.",
        category: "ai",
        level: "advanced",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Dark%20AI/Thumbnail/Dark%20Ai%2004.png",
        slug: "dark-ai",
        updated_at: new Date().toISOString(),
    },
    {
        id: "digital-arrest",
        name: "Digital Arrest",
        description: "Understand digital arrest scams and learn how to protect yourself and your organization from this emerging fraud technique.",
        category: "security",
        level: "intermediate",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Digital%20Arrest%20Scam/Thumbnail/Digital%20Arrest%204.png",
        slug: "digital-arrest",
        updated_at: new Date().toISOString(),
    },
];


export const courseFilterGroups: FilterGroup[] = [
  {
    title: "Category",
    key: "category",
    options: [
      { label: "Security", value: "security", count: 67 },
      { label: "AI", value: "ai", count: 12 },
      { label: "Development", value: "development", count: 4 },
    ],
  },
  {
    title: "Level",
    key: "level",
    options: [
      { label: "Beginner", value: "beginner", count: 21 },
      { label: "Intermediate", value: "intermediate", count: 47 },
      { label: "Advanced", value: "advanced", count: 16 },
    ],
  },
  {
    title: "Language",
    key: "language",
    options: [
      { label: "English", value: "english", count: 62 },
      { label: "Hindi", value: "hindi", count: 22 },
    ],
  },
  {
    title: "Topic",
    key: "topic",
    options: [
      { label: "Phishing & Email Security", value: "phishing-email", count: 8 },
      { label: "Malware & Attacks", value: "malware-attacks", count: 15 },
      { label: "Password & Authentication", value: "password-auth", count: 5 },
      { label: "AI & Machine Learning", value: "ai-ml", count: 12 },
      { label: "Workplace Security", value: "workplace", count: 10 },
      { label: "Cyber Hygiene", value: "cyber-hygiene", count: 7 },
      { label: "Scams & Fraud", value: "scams-fraud", count: 11 },
      { label: "Network Security", value: "network", count: 4 },
      { label: "Development", value: "development", count: 4 },
    ],
  },
  {
    title: "Duration",
    key: "duration",
    options: [
      { label: "Short (< 5 min)", value: "short", count: 28 },
      { label: "Medium (5-10 min)", value: "medium", count: 42 },
      { label: "Long (> 10 min)", value: "long", count: 14 },
    ],
  },
];