import { Course, FilterObject } from "@/types";

export const dummyCourses: Course[] = [
    {
        id: "one-time-password",
        name: "One Time Password",
        description: "Learn about One Time Password (OTP) security mechanisms and best practices for implementing secure authentication systems.",
        category: "security",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/One%20Time%20Password/One%20time%20password%20-%20thumbnail.png",
        updated_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: "work-from-home-jobs",
        name: "Work From Home Jobs",
        description: "Understand security risks and best practices when working from home, including protecting company data and maintaining secure remote connections.",
        category: "security",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/WFH%20Security%20Tips/WFH%20Security%20Tips%20Thumbnail.png",
        updated_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: "business-email-compromise",
        name: "Business Email Compromise",
        description: "Learn to identify and prevent Business Email Compromise attacks, protecting your organization from email-based fraud and social engineering.",
        category: "security",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/BEC/Thumbnail/BEC%201.png",
        updated_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: "browser-extension",
        name: "Browser Extension",
        description: "Understand the security implications of browser extensions, including safe browsing practices and identifying potentially malicious extensions.",
        category: "ai",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Browser%20Extension/Thumbnail/Browser%20Extensions%20(1).png",
        updated_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: "clickjacking",
        name: "Clickjacking",
        description: "Learn about clickjacking attacks and how to protect users from this deceptive web-based attack technique.",
        category: "security",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Clickjacking/Thumbnail/1%20Video%20Thumbnails.png",
        updated_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: "ceo-fraud",
        name: "CEO Fraud",
        description: "Understand CEO fraud tactics and learn to identify and prevent executive impersonation attacks targeting organizations.",
        category: "security",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Cybersecurity%20awareness%20CEO%20fraud/Cybersecurity%20awareness%20CEO%20fraud.png",
        updated_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: "generative-ai",
        name: "Generative AI",
        description: "Explore the security implications and best practices for using generative AI tools in the workplace safely and responsibly.",
        category: "ai",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Generative%20AI/Thumbnail/Generative%20AI%20in%20Cybersecurity%201.png",
        updated_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: "harpstrings",
        name: "Harpstrings",
        description: "Learn about harpstrings security concepts and implementing effective security measures in your organization.",
        category: "security",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Malvertising/Malvertising%20Thumbnail.png",
        updated_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: "information-security",
        name: "Information Security",
        description: "Comprehensive introduction to information security principles, covering essential security awareness topics for all employees.",
        category: "security",   
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Information%20Security%20Awareness/Information%20Security%20Awareness%20-%20Thumbnail.png",
        updated_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: "physical-security",
        name: "Physical Security",
        description: "Learn about physical security measures to protect your workplace, including access control and security best practices.",
        category: "security",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Physical%20Attack/Physical%20Attack%20Thumbnail.png",
        updated_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: "insider-threat",
        name: "Insider Threat",
        description: "Understand insider threats, including red flags and real cases, and learn how to identify and defend against internal security risks.",
        category: "security",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Insider%20Threats/Thumbnail/Insider%20Threat%2004.png",
        updated_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: "phishing",
        name: "Phishing",
        description: "Learn to identify and defend against phishing attacks, including various types of phishing threats and social engineering tactics.",
        category: "security",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Phishing/Phishing%20Thumbnail.png",
        updated_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: "adware-in-the-workplace",
        name: "Adware in the Workplace",
        description: "Learn how to identify and prevent adware infections in workplace devices and understand security risks associated with adware.",
        category: "security",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Adware%20in%20the%20Workplace/Thumbnails/Adware%204.png",
        updated_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: "backdoor-attacks",
        name: "Backdoor Attacks",
        description: "Understand backdoor attacks, how they work, and learn effective techniques to secure systems and prevent unauthorized access.",
        category: "security",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Backdoor%20Attacks/Thumbnails/Backdoor%204.png",
        updated_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: "brute-force",
        name: "Brute Force",
        description: "Learn about brute force attacks, password security, and how to implement strong authentication measures to protect against these attacks.",
        category: "security",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Brute%20force%20Attack/Thumbnail/Brute%20Force%20Attack%204.png",
        updated_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: "cyber-hygiene",
        name: "Cyber Hygiene",
        description: "Learn essential cyber hygiene practices including password management, software updates, and maintaining good security habits.",
        category: "security",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Cyber%20Hygiene/Thumbnail/Cyber%20Hygiene%204.png",
        updated_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: "dark-ai",
        name: "Dark AI",
        description: "Explore the darker side of AI technology, understanding threats and defenses against malicious use of artificial intelligence.",
        category: "ai",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Dark%20AI/Thumbnail/Dark%20Ai%2004.png",
        updated_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: "digital-arrest",
        name: "Digital Arrest",
        description: "Understand digital arrest scams and learn how to protect yourself and your organization from this emerging fraud technique.",
        category: "security",
        thumbnail: "https://pub-75cc0f33e91642d886ed4f7aaa225686.r2.dev/Digital%20Arrest%20Scam/Thumbnail/Digital%20Arrest%204.png",
        updated_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
];


export const courseFilterGroups: FilterObject[] = [
  {
    name: "Category",
    id: "category",
    options: [
      { name: "Security", id: "security" },
      { name: "AI", id: "ai" },
      { name: "Development", id: "development" },
    ],
  },
  {
    name: "Level",
    id: "level",
    options: [
      { name: "Beginner", id: "beginner" },
      { name: "Intermediate", id: "intermediate" },
      { name: "Advanced", id: "advanced" },
    ],
  },
  {
    name: "Language",
    id: "language",
    options: [
      { name: "English", id: "english" },
      { name: "Hindi", id: "hindi" },
    ],
  },
  {
    name: "Topic",
    id: "topic",
    options: [
      { name: "Phishing & Email Security", id: "phishing-email" },
      { name: "Malware & Attacks", id: "malware-attacks" },
      { name: "Password & Authentication", id: "password-auth" },
      { name: "AI & Machine Learning", id: "ai-ml" },
      { name: "Workplace Security", id: "workplace" },
      { name: "Cyber Hygiene", id: "cyber-hygiene" },
      { name: "Scams & Fraud", id: "scams-fraud" },
      { name: "Network Security", id: "network" },
      { name: "Development", id: "development" },
    ],
  },
  {
    name: "Duration",
    id: "duration",
    options: [
      { name: "Short (< 5 min)", id: "short" },
      { name: "Medium (5-10 min)", id: "medium" },
      { name: "Long (> 10 min)", id: "long" },
    ],
  },
];