import { Employee } from "@/types";
import { id } from "date-fns/locale";

export const employees: Employee[] = [
  {
    id: "1",
    name: "Rajesh Kumar",
    email: "rajesh.kumar@example.com",
    role: "Senior Developer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
    riskLevel: "low",
  },
  {
    id: "2",
    name: "Priya Sharma",
    email: "priya.sharma@example.com",
    role: "UI/UX Designer",
    status: "active",
    department: "Design",
    groupsAssigned: [],
    riskLevel: "low",
  },
  {
    id: "3",
    name: "Amit Patel",
    email: "amit.patel@example.com",
    role: "Project Manager",
    status: "active",
    department: "Management",
    groupsAssigned: [],
    riskLevel: "low",
  },
  {
    id: "4",
    name: "Sneha Reddy",
    email: "sneha.reddy@example.com",
    role: "Full Stack Developer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
    riskLevel: "low",
  },
  {
    id: "5",
    name: "Vikram Singh",
    email: "vikram.singh@example.com",
    role: "DevOps Engineer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
    riskLevel: "low",
  },
  {
    id: "6",
    name: "Ananya Iyer",
    email: "ananya.iyer@example.com",
    role: "Graphic Designer",
    status: "active",
    department: "Design",
    groupsAssigned: [],
    riskLevel: "low",
  },
  {
    id: "7",
    name: "Arjun Mehta",
    email: "arjun.mehta@example.com",
    role: "Backend Developer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
    riskLevel: "low",
  },
  {
    id: "8",
    name: "Deepika Nair",
    email: "deepika.nair@example.com",
    role: "Product Manager",
    status: "active",
    department: "Management",
    groupsAssigned: [],
    riskLevel: "low",
  },
  {
    id: "9",
    name: "Sanjay Gupta",
    email: "sanjay.gupta@example.com",
    role: "QA Engineer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
    riskLevel: "low",
  },
  {
    id: "10",
    name: "Kavya Desai",
    email: "kavya.desai@example.com",
    role: "Frontend Developer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
    riskLevel: "medium",
  },
  {
    id: "11",
    name: "Rahul Verma",
    email: "rahul.verma@example.com",
    role: "Data Analyst",
    status: "active",
    department: "Analytics",
    groupsAssigned: [],
    riskLevel: "medium",
  },
  {
    id: "12",
    name: "Pooja Joshi",
    email: "pooja.joshi@example.com",
    role: "HR Manager",
    status: "active",
    department: "Human Resources",
    groupsAssigned: [],
    riskLevel: "medium",
  },
  {
    id: "13",
    name: "Karan Malhotra",
    email: "karan.malhotra@example.com",
    role: "Mobile Developer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
    riskLevel: "medium",
  },
  {
    id: "14",
    name: "Neha Kapoor",
    email: "neha.kapoor@example.com",
    role: "Content Writer",
    status: "active",
    department: "Marketing",
    groupsAssigned: [],
    riskLevel: "medium",
  },
  {
    id: "15",
    name: "Aditya Rao",
    email: "aditya.rao@example.com",
    role: "System Administrator",
    status: "active",
    department: "IT",
    groupsAssigned: [],
    riskLevel: "high",
  },
  {
    id: "16",
    name: "Riya Banerjee",
    email: "riya.banerjee@example.com",
    role: "Business Analyst",
    status: "active",
    department: "Analytics",
    groupsAssigned: [],
    riskLevel: "high",
  },
  {
    id: "17",
    name: "Manish Agarwal",
    email: "manish.agarwal@example.com",
    role: "Security Engineer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
    riskLevel: "high",
  },
  {
    id: "18",
    name: "Ishita Sinha",
    email: "ishita.sinha@example.com",
    role: "UX Researcher",
    status: "active",
    department: "Design",
    groupsAssigned: [],
    riskLevel: "high",
  },
  {
    id: "19",
    name: "Rohit Bhatt",
    email: "rohit.bhatt@example.com",
    role: "Cloud Architect",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
    riskLevel: "high",
  },
  {
    id: "20",
    name: "Simran Kaur",
    email: "simran.kaur@example.com",
    role: "Digital Marketing Specialist",
    status: "active",
    department: "Marketing",
    groupsAssigned: [],
    riskLevel: "high",
  },
  {
    id: "21",
    name: "Varun Khanna",
    email: "varun.khanna@example.com",
    role: "Machine Learning Engineer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
    riskLevel: "high",
  },
  {
    id: "22",
    name: "Tanvi Saxena",
    email: "tanvi.saxena@example.com",
    role: "Scrum Master",
    status: "active",
    department: "Management",
    groupsAssigned: [],
    riskLevel: "high",
  },
  {
    id: "23",
    name: "Nikhil Pandey",
    email: "nikhil.pandey@example.com",
    role: "Database Administrator",
    status: "active",
    department: "IT",
    groupsAssigned: [],
    riskLevel: "high",
  },
  {
    id: "24",
    name: "Aditi Mishra",
    email: "aditi.mishra@example.com",
    role: "Sales Executive",
    status: "active",
    department: "Sales",
    groupsAssigned: [],
    riskLevel: "high",
  },
  {
    id: "25",
    name: "Siddharth Jain",
    email: "siddharth.jain@example.com",
    role: "Technical Lead",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
    riskLevel: "high",
  },
  {
    id: "26",
    name: "Meera Pillai",
    email: "meera.pillai@example.com",
    role: "Finance Manager",
    status: "active",
    department: "Finance",
    groupsAssigned: [],
    riskLevel: "high",
  },
  {
    id: "27",
    name: "Kunal Shah",
    email: "kunal.shah@example.com",
    role: "Product Designer",
    status: "active",
    department: "Design",
    groupsAssigned: [],
    riskLevel: "high",
  },
  {
    id: "28",
    name: "Divya Menon",
    email: "divya.menon@example.com",
    role: "Customer Success Manager",
    status: "active",
    department: "Customer Support",
    groupsAssigned: [],
    riskLevel: "high",
  },
  {
    id: "29",
    name: "Abhishek Trivedi",
    email: "abhishek.trivedi@example.com",
    role: "Network Engineer",
    status: "active",
    department: "IT",
    groupsAssigned: [],
  },
  {
    id: "30",
    name: "Shruti Yadav",
    email: "shruti.yadav@example.com",
    role: "Legal Advisor",
    status: "active",
    department: "Legal",
    groupsAssigned: [],
  },
  {
    id: "31",
    name: "Akash Dubey",
    email: "akash.dubey@example.com",
    role: "iOS Developer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "32",
    name: "Nisha Choudhary",
    email: "nisha.choudhary@example.com",
    role: "Recruitment Specialist",
    status: "active",
    department: "Human Resources",
    groupsAssigned: [],
  },
  {
    id: "33",
    name: "Gaurav Bhatia",
    email: "gaurav.bhatia@example.com",
    role: "Solutions Architect",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "34",
    name: "Anjali Tiwari",
    email: "anjali.tiwari@example.com",
    role: "Social Media Manager",
    status: "active",
    department: "Marketing",
    groupsAssigned: [],
  },
  {
    id: "35",
    name: "Harsh Soni",
    email: "harsh.soni@example.com",
    role: "Android Developer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "36",
    name: "Sakshi Rathi",
    email: "sakshi.rathi@example.com",
    role: "Operations Manager",
    status: "active",
    department: "Operations",
    groupsAssigned: [],
  },
  {
    id: "37",
    name: "Yash Chopra",
    email: "yash.chopra@example.com",
    role: "Data Scientist",
    status: "active",
    department: "Analytics",
    groupsAssigned: [],
  },
  {
    id: "38",
    name: "Kritika Bose",
    email: "kritika.bose@example.com",
    role: "Brand Manager",
    status: "active",
    department: "Marketing",
    groupsAssigned: [],
  },
  {
    id: "39",
    name: "Rohan Mathur",
    email: "rohan.mathur@example.com",
    role: "Blockchain Developer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "40",
    name: "Pallavi Ghosh",
    email: "pallavi.ghosh@example.com",
    role: "Training Coordinator",
    status: "active",
    department: "Human Resources",
    groupsAssigned: [],
  },
  {
    id: "41",
    name: "Mohit Singhal",
    email: "mohit.singhal@example.com",
    role: "Site Reliability Engineer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "42",
    name: "Swati Kulkarni",
    email: "swati.kulkarni@example.com",
    role: "Compliance Officer",
    status: "active",
    department: "Legal",
    groupsAssigned: [],
  },
  {
    id: "43",
    name: "Piyush Goyal",
    email: "piyush.goyal@example.com",
    role: "AI Research Engineer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "44",
    name: "Vaishnavi Rane",
    email: "vaishnavi.rane@example.com",
    role: "Public Relations Manager",
    status: "active",
    department: "Marketing",
    groupsAssigned: [],
  },
  {
    id: "45",
    name: "Tarun Bhardwaj",
    email: "tarun.bhardwaj@example.com",
    role: "Performance Engineer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "46",
    name: "Preeti Ahluwalia",
    email: "preeti.ahluwalia@example.com",
    role: "Payroll Specialist",
    status: "active",
    department: "Finance",
    groupsAssigned: [],
  },
  {
    id: "47",
    name: "Vivek Chawla",
    email: "vivek.chawla@example.com",
    role: "Game Developer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "48",
    name: "Bhavna Sethi",
    email: "bhavna.sethi@example.com",
    role: "Event Manager",
    status: "active",
    department: "Marketing",
    groupsAssigned: [],
  },
  {
    id: "49",
    name: "Aman Chauhan",
    email: "aman.chauhan@example.com",
    role: "Quality Assurance Lead",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "50",
    name: "Jyoti Nagpal",
    email: "jyoti.nagpal@example.com",
    role: "Accounts Manager",
    status: "active",
    department: "Finance",
    groupsAssigned: [],
  },
  {
    id: "51",
    name: "Aryan Kohli",
    email: "aryan.kohli@example.com",
    role: "Frontend Engineer",
    status: "inactive",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "52",
    name: "Megha Rastogi",
    email: "megha.rastogi@example.com",
    role: "Visual Designer",
    status: "active",
    department: "Design",
    groupsAssigned: [],
  },
  {
    id: "53",
    name: "Sahil Dhawan",
    email: "sahil.dhawan@example.com",
    role: "Infrastructure Engineer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "54",
    name: "Radhika Tandon",
    email: "radhika.tandon@example.com",
    role: "Employee Relations Manager",
    status: "active",
    department: "Human Resources",
    groupsAssigned: [],
  },
  {
    id: "55",
    name: "Karthik Suresh",
    email: "karthik.suresh@example.com",
    role: "Technical Writer",
    status: "active",
    department: "Documentation",
    groupsAssigned: [],
  },
  {
    id: "56",
    name: "Sonali Batra",
    email: "sonali.batra@example.com",
    role: "Market Research Analyst",
    status: "active",
    department: "Analytics",
    groupsAssigned: [],
  },
  {
    id: "57",
    name: "Pranav Thakur",
    email: "pranav.thakur@example.com",
    role: "Embedded Systems Engineer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "58",
    name: "Aarti Srivastava",
    email: "aarti.srivastava@example.com",
    role: "Partnership Manager",
    status: "active",
    department: "Business Development",
    groupsAssigned: [],
  },
  {
    id: "59",
    name: "Sameer Khan",
    email: "sameer.khan@example.com",
    role: "Release Manager",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "60",
    name: "Ritika Ahuja",
    email: "ritika.ahuja@example.com",
    role: "SEO Specialist",
    status: "active",
    department: "Marketing",
    groupsAssigned: [],
  },
  {
    id: "61",
    name: "Nitin Bajaj",
    email: "nitin.bajaj@example.com",
    role: "API Developer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "62",
    name: "Tanya Arora",
    email: "tanya.arora@example.com",
    role: "Corporate Trainer",
    status: "inactive",
    department: "Human Resources",
    groupsAssigned: [],
  },
  {
    id: "63",
    name: "Ashwin Nambiar",
    email: "ashwin.nambiar@example.com",
    role: "Full Stack Engineer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "64",
    name: "Shweta Garg",
    email: "shweta.garg@example.com",
    role: "Risk Analyst",
    status: "active",
    department: "Finance",
    groupsAssigned: [],
  },
  {
    id: "65",
    name: "Suraj Pawar",
    email: "suraj.pawar@example.com",
    role: "Automation Engineer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "66",
    name: "Priyanka Bakshi",
    email: "priyanka.bakshi@example.com",
    role: "Communications Manager",
    status: "active",
    department: "Marketing",
    groupsAssigned: [],
  },
  {
    id: "67",
    name: "Sumit Deshpande",
    email: "sumit.deshpande@example.com",
    role: "Backend Engineer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "68",
    name: "Leena Saini",
    email: "leena.saini@example.com",
    role: "Talent Acquisition Lead",
    status: "active",
    department: "Human Resources",
    groupsAssigned: [],
  },
  {
    id: "69",
    name: "Dhruv Rawal",
    email: "dhruv.rawal@example.com",
    role: "Computer Vision Engineer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "70",
    name: "Shraddha Patil",
    email: "shraddha.patil@example.com",
    role: "Product Marketing Manager",
    status: "active",
    department: "Marketing",
    groupsAssigned: [],
  },
  {
    id: "71",
    name: "Kartik Mohan",
    email: "kartik.mohan@example.com",
    role: "Software Architect",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "72",
    name: "Aparna Dalal",
    email: "aparna.dalal@example.com",
    role: "Budget Analyst",
    status: "active",
    department: "Finance",
    groupsAssigned: [],
  },
  {
    id: "73",
    name: "Uday Shankar",
    email: "uday.shankar@example.com",
    role: "Test Automation Engineer",
    status: "inactive",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "74",
    name: "Madhuri Menon",
    email: "madhuri.menon@example.com",
    role: "Diversity & Inclusion Manager",
    status: "active",
    department: "Human Resources",
    groupsAssigned: [],
  },
  {
    id: "75",
    name: "Ravi Narayanan",
    email: "ravi.narayanan@example.com",
    role: "Platform Engineer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "76",
    name: "Geeta Vyas",
    email: "geeta.vyas@example.com",
    role: "Customer Support Lead",
    status: "active",
    department: "Customer Support",
    groupsAssigned: [],
  },
  {
    id: "77",
    name: "Alok Rastogi",
    email: "alok.rastogi@example.com",
    role: "Principal Engineer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "78",
    name: "Lakshmi Iyer",
    email: "lakshmi.iyer@example.com",
    role: "Supply Chain Manager",
    status: "active",
    department: "Operations",
    groupsAssigned: [],
  },
  {
    id: "79",
    name: "Ayush Kapoor",
    email: "ayush.kapoor@example.com",
    role: "DevSecOps Engineer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "80",
    name: "Nidhi Malhotra",
    email: "nidhi.malhotra@example.com",
    role: "Content Strategist",
    status: "active",
    department: "Marketing",
    groupsAssigned: [],
  },
  {
    id: "81",
    name: "Sandeep Rawat",
    email: "sandeep.rawat@example.com",
    role: "Site Manager",
    status: "active",
    department: "Operations",
    groupsAssigned: [],
  },
  {
    id: "82",
    name: "Amrita Kohli",
    email: "amrita.kohli@example.com",
    role: "Motion Graphics Designer",
    status: "active",
    department: "Design",
    groupsAssigned: [],
  },
  {
    id: "83",
    name: "Vishal Bajpai",
    email: "vishal.bajpai@example.com",
    role: "Java Developer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "84",
    name: "Ritu Bhalla",
    email: "ritu.bhalla@example.com",
    role: "Learning & Development Manager",
    status: "active",
    department: "Human Resources",
    groupsAssigned: [],
  },
  {
    id: "85",
    name: "Mayank Mahajan",
    email: "mayank.mahajan@example.com",
    role: "Python Developer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "86",
    name: "Shilpa Deshmukh",
    email: "shilpa.deshmukh@example.com",
    role: "Procurement Officer",
    status: "inactive",
    department: "Operations",
    groupsAssigned: [],
  },
  {
    id: "87",
    name: "Naveen Reddy",
    email: "naveen.reddy@example.com",
    role: "Security Analyst",
    status: "active",
    department: "IT",
    groupsAssigned: [],
  },
  {
    id: "88",
    name: "Rashmi Saxena",
    email: "rashmi.saxena@example.com",
    role: "Email Marketing Specialist",
    status: "active",
    department: "Marketing",
    groupsAssigned: [],
  },
  {
    id: "89",
    name: "Deepak Agarwal",
    email: "deepak.agarwal@example.com",
    role: "React Developer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "90",
    name: "Kavita Dutta",
    email: "kavita.dutta@example.com",
    role: "Internal Auditor",
    status: "active",
    department: "Finance",
    groupsAssigned: [],
  },
  {
    id: "91",
    name: "Himanshu Grover",
    email: "himanshu.grover@example.com",
    role: "Unity Developer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "92",
    name: "Sangeeta Tripathi",
    email: "sangeeta.tripathi@example.com",
    role: "Office Manager",
    status: "active",
    department: "Administration",
    groupsAssigned: [],
  },
  {
    id: "93",
    name: "Chirag Parikh",
    email: "chirag.parikh@example.com",
    role: "NLP Engineer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "94",
    name: "Vandana Krishnan",
    email: "vandana.krishnan@example.com",
    role: "Client Relations Manager",
    status: "active",
    department: "Customer Support",
    groupsAssigned: [],
  },
  {
    id: "95",
    name: "Lalit Sharma",
    email: "lalit.sharma@example.com",
    role: "Node.js Developer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "96",
    name: "Sunita Puri",
    email: "sunita.puri@example.com",
    role: "Compensation Analyst",
    status: "active",
    department: "Human Resources",
    groupsAssigned: [],
  },
  {
    id: "97",
    name: "Ankit Bajwa",
    email: "ankit.bajwa@example.com",
    role: "Penetration Tester",
    status: "active",
    department: "IT",
    groupsAssigned: [],
  },
  {
    id: "98",
    name: "Urmila Pande",
    email: "urmila.pande@example.com",
    role: "Copywriter",
    status: "inactive",
    department: "Marketing",
    groupsAssigned: [],
  },
  {
    id: "99",
    name: "Manoj Kumar",
    email: "manoj.kumar@example.com",
    role: "Angular Developer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "100",
    name: "Varsha Jain",
    email: "varsha.jain@example.com",
    role: "Tax Consultant",
    status: "active",
    department: "Finance",
    groupsAssigned: [],
  },
  {
    id: "101",
    name: "Shashank Tiwari",
    email: "shashank.tiwari@example.com",
    role: "IoT Engineer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "102",
    name: "Archana Singh",
    email: "archana.singh@example.com",
    role: "Facilities Manager",
    status: "active",
    department: "Administration",
    groupsAssigned: [],
  },
  {
    id: "103",
    name: "Hemant Shukla",
    email: "hemant.shukla@example.com",
    role: "GraphQL Developer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "104",
    name: "Pratibha Mishra",
    email: "pratibha.mishra@example.com",
    role: "Strategic Planning Manager",
    status: "active",
    department: "Management",
    groupsAssigned: [],
  },
  {
    id: "105",
    name: "Ranjit Singh",
    email: "ranjit.singh@example.com",
    role: "Vue.js Developer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "106",
    name: "Kamini Rao",
    email: "kamini.rao@example.com",
    role: "Benefits Administrator",
    status: "active",
    department: "Human Resources",
    groupsAssigned: [],
  },
  {
    id: "107",
    name: "Tushar Dixit",
    email: "tushar.dixit@example.com",
    role: "Kubernetes Engineer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "108",
    name: "Seema Chandran",
    email: "seema.chandran@example.com",
    role: "Sales Operations Manager",
    status: "active",
    department: "Sales",
    groupsAssigned: [],
  },
  {
    id: "109",
    name: "Raghav Bose",
    email: "raghav.bose@example.com",
    role: "WebGL Developer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "110",
    name: "Shobha Menon",
    email: "shobha.menon@example.com",
    role: "Change Management Lead",
    status: "active",
    department: "Management",
    groupsAssigned: [],
  },
  {
    id: "111",
    name: "Prateek Bansal",
    email: "prateek.bansal@example.com",
    role: "Rust Developer",
    status: "inactive",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "112",
    name: "Poonam Ghosh",
    email: "poonam.ghosh@example.com",
    role: "Knowledge Manager",
    status: "active",
    department: "Documentation",
    groupsAssigned: [],
  },
  {
    id: "113",
    name: "Lokesh Vij",
    email: "lokesh.vij@example.com",
    role: "Go Developer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "114",
    name: "Rekha Pandey",
    email: "rekha.pandey@example.com",
    role: "Vendor Manager",
    status: "active",
    department: "Operations",
    groupsAssigned: [],
  },
  {
    id: "115",
    name: "Saurabh Kapur",
    email: "saurabh.kapur@example.com",
    role: "Swift Developer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "116",
    name: "Namrata Gupta",
    email: "namrata.gupta@example.com",
    role: "Process Improvement Manager",
    status: "active",
    department: "Operations",
    groupsAssigned: [],
  },
  {
    id: "117",
    name: "Puneet Malik",
    email: "puneet.malik@example.com",
    role: "Kotlin Developer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "118",
    name: "Sunaina Agnihotri",
    email: "sunaina.agnihotri@example.com",
    role: "Investor Relations Manager",
    status: "active",
    department: "Finance",
    groupsAssigned: [],
  },
  {
    id: "119",
    name: "Anuj Chaturvedi",
    email: "anuj.chaturvedi@example.com",
    role: "Scala Developer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "120",
    name: "Vineeta Saxena",
    email: "vineeta.saxena@example.com",
    role: "Employee Wellness Coordinator",
    status: "active",
    department: "Human Resources",
    groupsAssigned: [],
  },
  {
    id: "121",
    name: "Harshit Bahl",
    email: "harshit.bahl@example.com",
    role: "TypeScript Developer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "122",
    name: "Yamini Nambiar",
    email: "yamini.nambiar@example.com",
    role: "Sustainability Manager",
    status: "active",
    department: "Operations",
    groupsAssigned: [],
  },
  {
    id: "123",
    name: "Akshat Raina",
    email: "akshat.raina@example.com",
    role: "Flutter Developer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
  {
    id: "124",
    name: "Sarika Chawla",
    email: "sarika.chawla@example.com",
    role: "Corporate Social Responsibility Manager",
    status: "active",
    department: "Management",
    groupsAssigned: [],
  },
  {
    id: "125",
    name: "Krish Doshi",
    email: "krish.doshi@example.com",
    role: "React Native Developer",
    status: "active",
    department: "Engineering",
    groupsAssigned: [],
  },
];
