// import { EmployeeGroup } from "@/types";
// // import { employees } from "./employees";

// export const groups: EmployeeGroup[] = [
//   {
//     id: "eg-1",
//     name: "Engineering Team",
//     description: "Core engineering and development team",
//     memberCount: 15,
//     department: "Engineering",
//     status: "active",
//     createdAt: 1748226600000,
//     members: [],
//     riskLevel: "high",
//   },
//   {
//     id: "eg-2",
//     name: "Design Team",
//     description: "UI/UX and product design",
//     memberCount: 8,
//     department: "Design",
//     status: "active",
//     createdAt: 1748226600000,
//     members:  [],
//     riskLevel: "medium",
//   },
//   {
//     id: "eg-3",
//     name: "Product Management",
//     description: "Product strategy and roadmap",
//     memberCount: 5,
//     department: "Product",
//     status: "active",
//     createdAt: 1748226600000,
//     members: [],
//     riskLevel: "low",
//   },
//   {
//     id: "eg-4",
//     name: "Marketing Team",
//     description: "Marketing and growth initiatives",
//     memberCount: 12,
//     department: "Marketing",
//     status: "active",
//     createdAt: 1748226600000,
//     members: [],
//     riskLevel: "medium",
//   },
//   {
//     id: "eg-5",
//     name: "Sales Team",
//     description: "Business development and sales",
//     memberCount: 10,
//     department: "Sales",
//     status: "active",
//     createdAt: 1748226600000,
//     members: [],
//     riskLevel: "low",
//   },
//   {
//     id: "eg-6",
//     name: "HR & People Ops",
//     description: "Human resources and operations",
//     memberCount: 6,
//     department: "HR",
//     status: "active",
//     createdAt: 1748226600000,
//     members: [],
//     riskLevel: "low",
//   },
//   {
//     id: "eg-7",
//     name: "Finance Team",
//     description: "Financial planning and accounting",
//     memberCount: 7,
//     department: "Finance",
//     status: "active",
//     createdAt: 1748226600000,
//     members: [],
//     riskLevel: "low",
//   },
//   {
//     id: "eg-8",
//     name: "Customer Support",
//     description: "Customer success and support",
//     memberCount: 14,
//     department: "Support",
//     status: "active",
//     createdAt: 1748226600000,
//     members: [],
//     riskLevel: "low",
//   },
//   {
//     id: "eg-9",
//     name: "DevOps Team",
//     description: "Infrastructure and deployment",
//     memberCount: 4,
//     department: "Engineering",
//     status: "active",
//     createdAt: 1748226600000,
//     members: [],
//     riskLevel: "high",
//   },
//   {
//     id: "eg-10",
//     name: "QA Team",
//     description: "Quality assurance and testing",
//     memberCount: 6,
//     department: "Engineering",
//     status: "active",
//     createdAt: 1748226600000,
//     members: [],
//     riskLevel: "medium",
//   },
//   {
//     id: "eg-11",
//     name: "Content Team",
//     description: "Content creation and strategy",
//     memberCount: 5,
//     department: "Marketing",
//     status: "inactive",
//     createdAt: 1748226600000,
//     members: [],
//     riskLevel: "high",
//   },
//   {
//     id: "eg-12",
//     name: "Data Analytics",
//     description: "Data analysis and insights",
//     memberCount: 8,
//     department: "Product",
//     status: "inactive",
//     createdAt: 1748226600000,
//     members: [],
//     riskLevel: "low",
//   },
// ]