import { Group } from "@/types";

export const groups: Group[] = [
  {
    id: "eg-1",
    name: "Engineering Team",
    description: "Core engineering and development team",
    memberCount: 15,
    department: "Engineering",
    status: "active",
    createdAt: "2024-01-15",
    members: ["John Doe", "Alice Williams", "Charlie Brown"],
  },
  {
    id: "eg-2",
    name: "Design Team",
    description: "UI/UX and product design",
    memberCount: 8,
    department: "Design",
    status: "active",
    createdAt: "2024-01-20",
    members: ["Jane Smith", "Charlie Brown"],
  },
  {
    id: "eg-3",
    name: "Product Management",
    description: "Product strategy and roadmap",
    memberCount: 5,
    department: "Product",
    status: "active",
    createdAt: "2024-02-01",
    members: ["Bob Johnson"],
  },
  {
    id: "eg-4",
    name: "Marketing Team",
    description: "Marketing and growth initiatives",
    memberCount: 12,
    department: "Marketing",
    status: "active",
    createdAt: "2024-02-10",
    members: ["Sarah Connor", "Mike Ross"],
  },
  {
    id: "eg-5",
    name: "Sales Team",
    description: "Business development and sales",
    memberCount: 10,
    department: "Sales",
    status: "active",
    createdAt: "2024-02-15",
    members: ["Harvey Specter", "Donna Paulsen"],
  },
  {
    id: "eg-6",
    name: "HR & People Ops",
    description: "Human resources and operations",
    memberCount: 6,
    department: "HR",
    status: "active",
    createdAt: "2024-03-01",
    members: ["Jessica Pearson"],
  },
  {
    id: "eg-7",
    name: "Finance Team",
    description: "Financial planning and accounting",
    memberCount: 7,
    department: "Finance",
    status: "active",
    createdAt: "2024-03-05",
    members: ["Louis Litt", "Rachel Zane"],
  },
  {
    id: "eg-8",
    name: "Customer Support",
    description: "Customer success and support",
    memberCount: 14,
    department: "Support",
    status: "active",
    createdAt: "2024-03-10",
    members: ["Katrina Bennett"],
  },
  {
    id: "eg-9",
    name: "DevOps Team",
    description: "Infrastructure and deployment",
    memberCount: 4,
    department: "Engineering",
    status: "active",
    createdAt: "2024-03-15",
    members: ["Marcus Rashford"],
  },
  {
    id: "eg-10",
    name: "QA Team",
    description: "Quality assurance and testing",
    memberCount: 6,
    department: "Engineering",
    status: "active",
    createdAt: "2024-03-20",
    members: ["Bruno Fernandes"],
  },
  {
    id: "eg-11",
    name: "Content Team",
    description: "Content creation and strategy",
    memberCount: 5,
    department: "Marketing",
    status: "inactive",
    createdAt: "2024-04-01",
    members: ["Casemiro"],
  },
  {
    id: "eg-12",
    name: "Data Analytics",
    description: "Data analysis and insights",
    memberCount: 8,
    department: "Product",
    status: "inactive",
    createdAt: "2024-04-05",
    members: ["Antony"],
  },
]